r115 bravo one six bravo

diff --git a/scripts/fix-and-commit b/scripts/fix-and-commit
--- a/scripts/fix-and-commit
+++ b/scripts/fix-and-commit
@@ -24,6 +24,9 @@ if ! [[ -z "$(git status -s -uall)" ]]; then
     git push github HEAD:${GITHUB_REF}
 
     git checkout HEAD~
+
+    echo "checks failed, but fixed automatically committed"
+    exit 1
 else
     echo "no changes to commit"
 fi
